# Generated by Django 3.0.8 on 2020-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="branch",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="city",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="district",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
